# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: me@test.com
author_name: My Name
has_binder: false
has_settings: false
kind: frontend
labextension_name: step_counter
project_short_description: Adds a step counter/button, and a step increment provider
    (1 of 3 related examples). This extension holds a provider token.
python_name: step_counter
repository: ''
test: true

